---
abstract: 'create a XML::RSS object out of an Atom feed'
author:
  - 'Stephen Cardie <stephenca@ls26.net>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-RSS-FromAtom
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  XML::RSS::FromAtom:
    file: lib/XML/RSS/FromAtom.pm
    version: 0.02_02
requires:
  DateTime: 0
  DateTime::Format::ISO8601: 0
  DateTime::Format::Mail: 0
  Moo: 0
  Try::Tiny: 0
  XML::Atom::Syndication::Feed: 0
  XML::RSS: 0
  common::sense: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=XML-RSS-FromAtom
version: 0.02_02
