# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-FromAtom
version:      0.02
version_from: lib/XML/RSS/FromAtom.pm
installdirs:  site
requires:
    Class::Accessor:               0
    DateTime:                      0
    DateTime::Format::ISO8601:     0
    DateTime::Format::Mail:        0
    Test::More:                    0
    XML::Atom::Syndication:        0
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
